# Generated by Django 3.0.7 on 2020-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='UserName')),
                ('telegramid', models.TextField(db_column='TelegramId')),
                ('discordid', models.TextField(db_column='DiscordId')),
            ],
        ),
    ]
