# Generated by Django 3.0.6 on 2020-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPlatformApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discordid',
            field=models.CharField(db_column='DiscordId', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegramid',
            field=models.CharField(db_column='TelegramId', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(db_column='UserId', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='UserName', max_length=20),
        ),
    ]
