# Generated by Django 3.0.7 on 2020-06-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainPlatformApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.AutoField(db_column='PositionId', primary_key=True, serialize=False)),
                ('position', models.IntegerField(db_column='Position')),
            ],
        ),
        migrations.CreateModel(
            name='UnitClasses',
            fields=[
                ('unitclassid', models.AutoField(db_column='UnitClassId', primary_key=True, serialize=False)),
                ('unitclassname', models.CharField(db_column='UnitClassName', max_length=30)),
                ('unitclassdescription', models.TextField(db_column='UnitClassDescription')),
                ('unitstarthealpoints', models.IntegerField(db_column='UnitStartHealPoints')),
                ('unitstartdefencepoints', models.IntegerField(db_column='UnitStartDefencePoints')),
                ('unitattackrange', models.IntegerField(db_column='UnitAttackRange')),
                ('unitattackcooldown', models.FloatField(db_column='UnitAttackCooldown')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitid', models.AutoField(db_column='UnitId', primary_key=True, serialize=False)),
                ('unitcustomname', models.CharField(db_column='UnitCustomName', max_length=30)),
                ('unitcurrhp', models.IntegerField(db_column='UnitCurrentHealPoints')),
                ('unitcurrdp', models.IntegerField(db_column='UnitCurrentDefencePoints')),
                ('unitclassid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.UnitClasses')),
            ],
        ),
        migrations.CreateModel(
            name='SessionMedievalBattle',
            fields=[
                ('sessionid', models.AutoField(db_column='SessionId', primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPlatformApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.SessionMedievalBattle')),
            ],
        ),
        migrations.CreateModel(
            name='MedievalBattle',
            fields=[
                ('gameid', models.AutoField(db_column='MedievalBattleId', primary_key=True, serialize=False)),
                ('sessionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.SessionMedievalBattle')),
            ],
        ),
        migrations.CreateModel(
            name='MapPositions',
            fields=[
                ('mappositionsid', models.AutoField(db_column='MapPositionsId', primary_key=True, serialize=False)),
                ('positionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.Position')),
                ('unitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.Unit')),
            ],
        ),
    ]
