# Generated by Django 3.0.6 on 2020-06-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPlatformApp', '0002_auto_20200612_1329'),
        ('MedievalBattleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappositions',
            name='positionid',
        ),
        migrations.RemoveField(
            model_name='mappositions',
            name='unitid',
        ),
        migrations.RemoveField(
            model_name='sessionmedievalbattle',
            name='userid',
        ),
        migrations.AddField(
            model_name='mappositions',
            name='playerid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.SessionMedievalBattle'),
        ),
        migrations.AddField(
            model_name='position',
            name='mappositionsid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.MapPositions'),
        ),
        migrations.AddField(
            model_name='unit',
            name='mappositionsid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.MapPositions'),
        ),
        migrations.AlterField(
            model_name='medievalbattle',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MedievalBattleApp.SessionMedievalBattle'),
        ),
        migrations.AlterField(
            model_name='player',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPlatformApp.User'),
        ),
        migrations.AlterField(
            model_name='unitclasses',
            name='unitclassid',
            field=models.AutoField(db_column='UnitClassId', primary_key=True, serialize=False, unique=True),
        ),
    ]
