// <auto-generated />
using System;
using Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200802105040_AddedMedievalBattleDatabaseToMainDB")]
    partial class AddedMedievalBattleDatabaseToMainDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.MapPositioning", b =>
                {
                    b.Property<int>("MapPositioningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("MapPositioningId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MapPositioning");
                });

            modelBuilder.Entity("Database.Models.MedievalBattle", b =>
                {
                    b.Property<int>("MedievalBatlleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SessionMedievalBattleId")
                        .HasColumnType("int");

                    b.Property<int?>("abstractFieldId")
                        .HasColumnType("int");

                    b.HasKey("MedievalBatlleId");

                    b.HasIndex("SessionMedievalBattleId")
                        .IsUnique();

                    b.HasIndex("abstractFieldId");

                    b.ToTable("MedievalBattles");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.AbstractField", b =>
                {
                    b.Property<int>("abstractFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalStatisticId")
                        .HasColumnType("int");

                    b.Property<int?>("abstractFieldId1")
                        .HasColumnType("int");

                    b.Property<int>("damagePerUnit")
                        .HasColumnType("int");

                    b.Property<int>("fieldArmor")
                        .HasColumnType("int");

                    b.Property<int>("fieldDamage")
                        .HasColumnType("int");

                    b.Property<int>("fieldHp")
                        .HasColumnType("int");

                    b.Property<int>("fieldSize")
                        .HasColumnType("int");

                    b.Property<int>("fieldUnitCount")
                        .HasColumnType("int");

                    b.Property<int?>("gameControllerId")
                        .HasColumnType("int");

                    b.Property<int>("hpPerUnit")
                        .HasColumnType("int");

                    b.Property<int>("positionId")
                        .HasColumnType("int");

                    b.Property<int>("teamId")
                        .HasColumnType("int");

                    b.Property<int>("unitCost")
                        .HasColumnType("int");

                    b.HasKey("abstractFieldId");

                    b.HasIndex("LocalStatisticId");

                    b.HasIndex("abstractFieldId1");

                    b.HasIndex("gameControllerId");

                    b.ToTable("AbstractFields");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractField");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.AliveField", b =>
                {
                    b.Property<int>("aliveFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fieldIndex")
                        .HasColumnType("int");

                    b.Property<int?>("gameControllerId")
                        .HasColumnType("int");

                    b.HasKey("aliveFieldId");

                    b.HasIndex("gameControllerId");

                    b.ToTable("aliveFieldsCount");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Coin", b =>
                {
                    b.Property<int>("coinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("gameControllerId")
                        .HasColumnType("int");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("coinId");

                    b.HasIndex("gameControllerId");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.GameController", b =>
                {
                    b.Property<int>("gameControllerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SessionMedievalBattleId")
                        .HasColumnType("int");

                    b.Property<int>("currentTurn")
                        .HasColumnType("int");

                    b.Property<int>("defeatTeam")
                        .HasColumnType("int");

                    b.Property<bool>("gameAvaliable")
                        .HasColumnType("bit");

                    b.HasKey("gameControllerId");

                    b.HasIndex("SessionMedievalBattleId");

                    b.ToTable("GameControllers");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.LocalStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("unitAliveCount")
                        .HasColumnType("int");

                    b.Property<int>("unitDeadCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LocalStatistic");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Unit", b =>
                {
                    b.Property<int>("unitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("armor")
                        .HasColumnType("int");

                    b.Property<int>("armorDurability")
                        .HasColumnType("int");

                    b.Property<int>("damage")
                        .HasColumnType("int");

                    b.Property<int>("hp")
                        .HasColumnType("int");

                    b.Property<int?>("parentObjectabstractFieldId")
                        .HasColumnType("int");

                    b.HasKey("unitId");

                    b.HasIndex("parentObjectabstractFieldId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleStats", b =>
                {
                    b.Property<int>("MedievalBattleStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MedievalBattleStatsId");

                    b.ToTable("MedievalBattleStats");
                });

            modelBuilder.Entity("Database.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MedievalBattleId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("MedievalBattleId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Database.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MapPositioningId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionNumber")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("MapPositioningId")
                        .IsUnique();

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Database.Models.SessionMedievalBattle", b =>
                {
                    b.Property<int>("SessionMedievalBattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SessionMedievalBattleId");

                    b.ToTable("SessionMedievalBattles");
                });

            modelBuilder.Entity("Database.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MapPositioningId")
                        .HasColumnType("int");

                    b.Property<int>("UnitCurrentDP")
                        .HasColumnType("int");

                    b.Property<int>("UnitCurrentHP")
                        .HasColumnType("int");

                    b.Property<string>("UnitCustomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.HasIndex("MapPositioningId")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Database.Models.UnitClasses", b =>
                {
                    b.Property<int>("UnitClassesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AttackCooldown")
                        .HasColumnType("real");

                    b.Property<float>("AttackRange")
                        .HasColumnType("real");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefencePoints")
                        .HasColumnType("int");

                    b.Property<int>("HealPoints")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("UnitClassesId");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("UnitClasses");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telegram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.Models.UserStatistics", b =>
                {
                    b.Property<int>("UserStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserStatisticsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStatistics");
                });

            modelBuilder.Entity("Database.Models.UsersSessionsMedievalBattle", b =>
                {
                    b.Property<int>("UsersSessionsMedievalBattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SessionMedievalBattleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UsersSessionsMedievalBattleId");

                    b.HasIndex("SessionMedievalBattleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersSessionsMedievalBattle");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Archer", b =>
                {
                    b.HasBaseType("Database.Models.MedievalBattleModels.AbstractField");

                    b.HasDiscriminator().HasValue("Archer");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Fighter", b =>
                {
                    b.HasBaseType("Database.Models.MedievalBattleModels.AbstractField");

                    b.HasDiscriminator().HasValue("Fighter");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Flank", b =>
                {
                    b.HasBaseType("Database.Models.MedievalBattleModels.AbstractField");

                    b.HasDiscriminator().HasValue("Flank");
                });

            modelBuilder.Entity("Database.Models.MapPositioning", b =>
                {
                    b.HasOne("Database.Models.Player", "Player")
                        .WithMany("MapPositionings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.MedievalBattle", b =>
                {
                    b.HasOne("Database.Models.SessionMedievalBattle", "SessionMedievalBattle")
                        .WithOne("MedievalBattle")
                        .HasForeignKey("Database.Models.MedievalBattle", "SessionMedievalBattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.MedievalBattleModels.AbstractField", "AbstractField")
                        .WithMany()
                        .HasForeignKey("abstractFieldId");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.AbstractField", b =>
                {
                    b.HasOne("Database.Models.MedievalBattleModels.LocalStatistic", "LocalStatistic")
                        .WithMany()
                        .HasForeignKey("LocalStatisticId");

                    b.HasOne("Database.Models.MedievalBattleModels.AbstractField", null)
                        .WithMany("Enemies")
                        .HasForeignKey("abstractFieldId1");

                    b.HasOne("Database.Models.MedievalBattleModels.GameController", "gameController")
                        .WithMany()
                        .HasForeignKey("gameControllerId");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.AliveField", b =>
                {
                    b.HasOne("Database.Models.MedievalBattleModels.GameController", null)
                        .WithMany("aliveFieldsCount")
                        .HasForeignKey("gameControllerId");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Coin", b =>
                {
                    b.HasOne("Database.Models.MedievalBattleModels.GameController", null)
                        .WithMany("coins")
                        .HasForeignKey("gameControllerId");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.GameController", b =>
                {
                    b.HasOne("Database.Models.SessionMedievalBattle", "sessionMedievalBattle")
                        .WithMany()
                        .HasForeignKey("SessionMedievalBattleId");
                });

            modelBuilder.Entity("Database.Models.MedievalBattleModels.Unit", b =>
                {
                    b.HasOne("Database.Models.MedievalBattleModels.AbstractField", "parentObject")
                        .WithMany("Units")
                        .HasForeignKey("parentObjectabstractFieldId");
                });

            modelBuilder.Entity("Database.Models.Player", b =>
                {
                    b.HasOne("Database.Models.MedievalBattle", "MedievalBattle")
                        .WithMany()
                        .HasForeignKey("MedievalBattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.Position", b =>
                {
                    b.HasOne("Database.Models.MapPositioning", "MapPositioning")
                        .WithOne("Position")
                        .HasForeignKey("Database.Models.Position", "MapPositioningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.Unit", b =>
                {
                    b.HasOne("Database.Models.MapPositioning", "MapPositioning")
                        .WithOne("Unit")
                        .HasForeignKey("Database.Models.Unit", "MapPositioningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.UnitClasses", b =>
                {
                    b.HasOne("Database.Models.Unit", "Unit")
                        .WithOne("UnitClasses")
                        .HasForeignKey("Database.Models.UnitClasses", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Models.UserStatistics", b =>
                {
                    b.HasOne("Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Database.Models.UsersSessionsMedievalBattle", b =>
                {
                    b.HasOne("Database.Models.SessionMedievalBattle", "SessionMedievalBattle")
                        .WithMany("UsersSessionsMedievalBattles")
                        .HasForeignKey("SessionMedievalBattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("usersSessionsMedievalBattles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
